### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Starcon79** [tdenolle/hassio-addons#1]
Is there a possibility to add the canister fill level? Also, a switch for automatic redox dosing would be useful.

Otherwise, thank you very much for providing the add-on.

Best regards,
Torsten

**Comment by tdenolle** [comment]
Hi @Starcon79, 'al_ph_minus_empty' message will be raised in sensor.bayrol_22aseXXXXX_messages entity when canister is empty. I'll think of it in the next release to have a dedicated sensor to supervise canister. 
Concerning switch, you'll find in in the next release.
